version: '3'

services:
  docs:
    image: fly_cookiecutter_django_local_docs
    container_name: fly_cookiecutter_django_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./fly_cookiecutter_django:/app/fly_cookiecutter_django:z
    ports:
      - '9000:9000'
    command: /start-docs
