# fly.toml app configuration file generated for django-rss-reader-3 on 2024-04-30T16:49:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-rss-reader-3'
primary_region = 'mad'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = "python manage.py migrate"

[processes]
  app = "python -m gunicorn --bind :8000 --workers 2 config.wsgi"
  worker = "python -m celery -A config.celery_app:app worker -l DEBUG"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static'
